### ISSUE TITLE
Allow to search for other technologies

### ISSUE THREAD

**Issue by piranna** [jamiebull1/remotor#5]
Specifically, allow to search for Node.js, or search for several technologies at once.

**Comment by jamiebull1** [comment]
Hi @piranna - I just pushed an update that opens up the background searches to other technologies, so you see node.js jobs, even if they don't mention Python. You can also search for several technologies at once from the Profile page when you're logged in.

**Comment by piranna** [comment]
Great! Thank you! :-D

**Comment by jamiebull1** [comment]
No problem!
